### ISSUE TITLE
3.13 5-1 Arch update

### ISSUE THREAD

**Issue by govg** [he1per/psmouse-dkms-alpsv7#1]
Hi,

I recently updated Arch, and realised my touchpad doesn't work as usual anymore. When will this be updated to the latest version?

**Comment by ismaelbej** [comment]
If you have installed a new kernel then you need to recompile and install again the module for the new kernel to be able to load it. Each module is installed in path with the version number included, ie /lib/modules/3.13-1-amd64/kernel/...
