### ISSUE TITLE
problem in ubuntu 14.04

### ISSUE THREAD

**Issue by benyaminsalimi** [he1per/psmouse-dkms-alpsv7#11]
hay guys i have little problem whit this mudel in ubuntu
i install : https://github.com/benyaminsalimi/psmouse-dkms-alpsv7
and its work fine untill i restart my laptop
after restart my lap top look like it dosent install this and i have to install this again
plz help me
sorry for my english :(

**Comment by erlanger** [comment]
Try the new version from https://github.com/he1per/psmouse-dkms-alpsv7 and see if it works.

**Comment by he1per** [comment]
closed, duplicate of #10
