### ISSUE TITLE
Change for newer Alps device

### ISSUE THREAD

**Issue by olivierb2** [he1per/psmouse-dkms-alpsv7#17]
Dear developper,

I'm very glad to find this project as my actual Alps device is not fully working properly (unable to have MultiTouch working). I just bought a brand new HP EliteBook Folio 1020 and my mouse is indentified as "Unknown ALPS toughpad: E7=10 00 64, EC=10 00 64.

Is there any way to add my device in this patch?

Please ask me if you need anything to be done on my computer.

Thanks and best regards.

Olivier

**Comment by olivierb2** [comment]
Just additional information:

After adding the line
    { { 0x10, 0x00, 0x64 }, 0x00, ALPS_PROTO_V2, 0xf8, 0xf8, ALPS_PASS | ALPS_DUALPOINT | ALPS_PS2_INTERLEAVED } /\* Folio 1020 */

My device seems detected in the kernel, but the two finger scrolling seems disabled in the Gnome mouse settings or using gpointing-device-settings.

Any idea why?

Thanks

Olivier

**Comment by olivierb2** [comment]
I'm still trying different combination, one more thing I forgot to mention, I got the message from the kernel on psmouse module load:

psmouse serio1: bad data from KBC - timeout

**Comment by olivierb2** [comment]
A new update, with this settings, I got having the option Multitouch enabled in Gpointing Device Settings.
        { { 0x10, 0x00, 0x64 }, 0x00, ALPS_PROTO_V6, 0xf8, 0xf8, ALPS_PASS | ALPS_BTNLESS },  /\* Folio 1020 */

I've also created an xorg.conf file with

Section "InputClass"
  Identifier    "Toughpad"
  Driver    "synaptics"
  MatchIsTouchPad   "yes"
  Driver          "synaptics"                     # required
  Option          "MinSpeed"              "0.5"
  Option          "MaxSpeed"              "1.0"
  Option          "AccelFactor"           "0.075"
  Option          "TapButton1"            "1"
  Option          "TapButton2"            "2"     # multitouch
  Option          "TapButton3"            "3"     # multitouch
  Option          "VertTwoFingerScroll"   "1"     # multitouch
  Option          "HorizTwoFingerScroll"  "1"     # multitouch
  Option          "VertEdgeScroll"        "1"
  Option          "CoastingSpeed"         "8"
  Option          "CornerCoasting"        "1"
  Option          "CircularScrolling"     "1"
  Option          "CircScrollTrigger"     "7"
  Option          "EdgeMotionUseAlways"   "1"
  Option          "LBCornerButton"        "8"     # browser "back" btn
  Option          "RBCornerButton"        "9"     # browser "forward" btn
EndSection

But unfortunatelly, for strange reason, the multi touch still not working, I will continue my investigation.

**Comment by olivierb2** [comment]
I've tried the kernel version 4.1~rc1 which brings a lot of code change for alps.o, unfortunatelly, my mouse still detected as Generic PS2.

**Comment by olivierb2** [comment]
Sorry, I close the issue as my device is definitely not an Alps device but Synaptics.

**Comment by tomposmiko** [comment]
@olivierb2 
In that case why did it detected az ALPS?
Anyway, I have the same issue on the same HW. Have you been able to get it work?

**Comment by olivierb2** [comment]
Hi,

The Alps code modules contains a small bug, but has been fixed in latest release, now it's simply detected as PS2 Mouse.
Regarding the support of the Synaptics, I opened a ticket at Kernel.org (you can see a lot of troubleshooting I already made), unfortunately, no answer yet.

https://bugzilla.kernel.org/show_bug.cgi?id=97751

This Synaptics must be detected on the i2c port (not over PS2 as it's now the case). I'm trying to debuging, but it remains complecated for me as I'm not a C developper.
