### ISSUE TITLE
Installation if psmouse-dkms-alpsv7 fails on Lenovo Z510

### ISSUE THREAD

**Issue by mynameisnotimportant** [he1per/psmouse-dkms-alpsv7#2]
Hello,

this solution doesn't work on my machine. I'm not very experienced in such things, pls help me.

dmesg output "psmouse serio1: alps: Unknown ALPS touchpad: E7=73 03 0a, EC=88 b6 06" led me here.

When following the instructions, this is what happens:

[me@localhost /]$ cd /tmp

[me@localhost tmp]$ git clone http://github.com/he1per/psmouse-dkms-alpsv7
Klone nach 'psmouse-dkms-alpsv7'... remote: Reusing existing pack: 87, done. remote: Total 87 (delta 0), reused 0 (delta 0) Unpacking objects: 100% (87/87), done. Prüfe Konnektivität... Fertig.

Creating symlink /var/lib/dkms/psmouse-dkms-alpsv7/1.0/source -> /usr/src/psmouse-dkms-alpsv7-1.0

DKMS: add completed. Error! echo Your kernel headers for kernel 3.13.5-200.fc20.x86_64 cannot be found at /lib/modules/3.13.5-200.fc20.x86_64/build or /lib/modules/3.13.5-200.fc20.x86_64/source. ▶▶▶▶ Error: Build failed

reboot doesn't change anything.

Trying to install again, it seems as if it was installed...:

[me@localhost psmouse-dkms-alpsv7]$ sudo ./install.sh
────── Building with dkms ───────

Error! DKMS tree already contains: psmouse-dkms-alpsv7-1.0
You cannot add the same module/version combo more than once.
Error! echo
Your kernel headers for kernel 3.13.5-200.fc20.x86_64 cannot be found at
/lib/modules/3.13.5-200.fc20.x86_64/build or /lib/modules/3.13.5-200.fc20.x86_64/source.
▶▶▶▶ Error: Build failed

Any suggestions?

Thank you in advance!

**Comment by ismaelbej** [comment]
The error message is saying that you are missing the kernel headers, for the installed kernel.
You didn't mention which distribution you are using, but you have to install a package named linux-headers or something simlilar.

**Comment by alehandrof** [comment]
FWIW, the error also indicates that the module has been installed before. You need to remove it prior to reinstallation:

```
sudo dkms remove psmouse-dkms-alpsv7/1.0 --all
```

(I still haven't gotten the module to _work_, but I think have its removal down :)

**Comment by he1per** [comment]
Thanks! @alehandrof  , I think you are already using some of the new patches from vincek, nonetheless try the new version and see if things work for you.

**Comment by he1per** [comment]
To the OP: you need to add linux-headers like @alehandrof mentioned.

**Comment by alehandrof** [comment]
@he1per FWIW I've been using 3.17+ versions of the kernel where this patch is not required for my device (Toshiba Z30-A)

Because a lot of the documentation on the internet points to this patch as a solution for getting ALPS to work, do you maybe want to add a word on the README about the fact that newer kernels do support it?

I found it easier to just stay on top of the [Ubuntu mainline kernels](https://wiki.ubuntu.com/Kernel/MainlineBuilds).

(Just an idea; that's why I didn't open an issue for this.)

**Comment by he1per** [comment]
Hi @alehandrof, thanks. I'll put something on the readme for the Toshiba Z30-A , the patch is needed for some other machines still.

**Comment by alehandrof** [comment]
I wasn't aware of that. Ignore my request.
