### ISSUE TITLE
Installation fails for Lenovo Flex 15

### ISSUE THREAD

**Issue by Drakuwa** [he1per/psmouse-dkms-alpsv7#5]
I've just did a clean install of Fedora 20 KDE spin on Lenovo Flex 15 ultrabook, and when I try to build the psmouse driver, I get:

make KERNELRELEASE=3.14.8-200.fc20.x86_64 -C /lib/modules/3.14.8-200.fc20.x86_64/build M=/var/lib/dkms/psmouse-dkms-alpsv7/1.0/build/src psmouse.ko.....
Error!  Build of psmouse.ko failed for: 3.14.8-200.fc20.x86_64 (x86_64)
Consult the make.log in the build directory

and this are the contents of the make.log:
DKMS make.log for psmouse-dkms-alpsv7-1.0 for kernel 3.14.8-200.fc20.x86_64 (x86_64)
Tue Jun 24 16:56:03 CEST 2014
make: Entering directory `/usr/src/kernels/3.14.8-200.fc20.x86_64'
  CC      /var/lib/dkms/psmouse-dkms-alpsv7/1.0/build/src/psmouse-base.o
  CC      /var/lib/dkms/psmouse-dkms-alpsv7/1.0/build/src/synaptics.o
  CC      /var/lib/dkms/psmouse-dkms-alpsv7/1.0/build/src/alps.o
  CC      /var/lib/dkms/psmouse-dkms-alpsv7/1.0/build/src/elantech.o
  CC      /var/lib/dkms/psmouse-dkms-alpsv7/1.0/build/src/logips2pp.o
  CC      /var/lib/dkms/psmouse-dkms-alpsv7/1.0/build/src/lifebook.o
  CC      /var/lib/dkms/psmouse-dkms-alpsv7/1.0/build/src/sentelic.o
  CC      /var/lib/dkms/psmouse-dkms-alpsv7/1.0/build/src/trackpoint.o
  CC      /var/lib/dkms/psmouse-dkms-alpsv7/1.0/build/src/cypress_ps2.o
  LD      /var/lib/dkms/psmouse-dkms-alpsv7/1.0/build/src/psmouse.o
  MODPOST 0 modules
make: Leaving directory`/usr/src/kernels/3.14.8-200.fc20.x86_64'

I have to say, I'm new to dkms and only know basic building/compiling

**Comment by Drakuwa** [comment]
Just another thing I saw in the RedHat bugzilla - https://bugzilla.redhat.com/show_bug.cgi?id=953211#c58 suggested adding a new device in the alps_model_data[] array in alsa.c. 

dmesg | grep psmouse
[    1.285690] psmouse serio1: alps: Unknown ALPS touchpad: E7=73 03 0a, EC=88 b6 06

This is what I get for my Unknown ALPS touchpad, so, what should I add in the array? { 0x73, 0x03, 0x0a }? What about the other values?

Thank you.

**Comment by kelteseth** [comment]
Same problem here und Ubuntu/ElementaryOS. My fix was to just install the latest daily mainline Linux kernel (Linux version 3.16.0-999-generic). Support for the new V7 was added a while ago -> https://github.com/torvalds/linux/commits/c309bfa9b481e7dbd3e1ab819271bf3009f44859/drivers/input/mouse/alps.c

**Comment by Drakuwa** [comment]
Thanks, you're right, the latest mainline Linux kernel did fix the problem.
